{
 "title": "Cloud Native Forensics - dotnet-core",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kubelet_node_name, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Application ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus: .NET Core: Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_request_duration_seconds_count{app=\"dotnet-core\"}[1m])) * 60",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Prometheus: .NET Core: 95th Percentile Response Time ",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{app=\"dotnet-core\"}[1m])) by (endpoint,le)) * 1000",
     "legendFormat": "{{endpoint}} "
    }
   ]
  },
  {
   "title": "Prometheus: .NET Core: API Throughput",
   "type": "stat",
   "description": "API request average ",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{app=\"dotnet-core\"}[1m])) * 60 "
    }
   ]
  },
  { "title": "Prometheus: Application Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 11, "x": 10, "y": 5 } },
  {
   "title": "Prometheus: .NET Core: Error Rate Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (endpoint)(rate(http_request_duration_seconds_count{app=\"dotnet-core\",code!=\"200\",endpoint!=\"/**\"}[1m])) * 60 ",
     "legendFormat": "{{endpoint}} "
    }
   ]
  },
  {
   "title": "Loki: Log Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (level) (rate({app=\"dotnet-core\"} | pattern `<date> <time>|<level>|<controller>|<message>` | level != \"\" [1s]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Loki: .NET Core Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{app=\"dotnet-core\"}"
    }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": ".NET Core: Total Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "(dotnet_total_memory_bytes{app=\"dotnet-core\"}) / 1e+6",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": ".NET Core: Live Threads",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 21 },
     "targets": [
      {
       "expr": "process_num_threads{app=\"dotnet-core\"}",
       "legendFormat": "instance"
      }
     ]
    },
    {
     "title": ".NET Core: CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 21 },
     "targets": [
      {
       "expr": "sum by (instance) (rate(process_cpu_seconds_total{app=\"dotnet-core\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "K8s: CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(container) (rate(container_cpu_usage_seconds_total{cluster=\"development\",namespace=\"default\",container=\"dotnet-core\"}[$__interval]))",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "K8s: Average Container Bandwidth by Namespace: Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 7, "x": 7, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "K8s: Average Container Bandwidth by Namespace: Received",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 7, "x": 14, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  }
 ]
}