name: .NET Core Delivery Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: us-central1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: se-jwilliams    # TODO: update to cluster name
  GKE_ZONE: us-central1-c   # TODO: update to cluster zone
  DEPLOYMENT_NAME: gke-dotnet-core # TODO: update to deployment name
  REPOSITORY: dotnet-core # TODO: update to Artifact Registry docker repository
  IMAGE: dotnet-core

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      # Alternative option - authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: Docker Login
      run: |-
        echo $GCP_CREDENTIALS | docker login -u _json_key --password-stdin https://$GAR_LOCATION-docker.pkg.dev  
    #- name: List work files
    #  run: |-
    #    cd dotnet-core; ls -R;
    - name: Build Docker Image
      run: |-
        cd dotnet-core; docker build -t dotnet-core:1.0 . --platform linux/amd64;
