name: Grafana Annotations

#on:
#  workflow_run:
#    workflows: [ ".NET Core Delivery Pipeline" ]
#    types: [completed]

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP: dotnet-core
  RELEASE_VERSION: 1.1
  GRAFANA_CLOUD_API_DOMAIN: ${{ secrets.GRAFANA_CLOUD_API_DOMAIN }}
  GRAFANA_CLOUD_API_KEY: ${{ secrets.GRAFANA_CLOUD_API_KEY }}
  
jobs:
  build:
    name: Create Releae Annotation
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Grafana API - Annotate
        run: |-
          curl -X POST $GRAFANA_CLOUD_API_DOMAIN/api/annotations \
          -H 'Accept: application/json' -H 'Content-Type: application/json' -H 'Authorization: Bearer ${{secrets.GRAFANA_CLOUD_API_KEY}}' \
          -d '{"tags":["app","$APP"],"text":"New Release Deployed - v$RELEASE_VERSION"}'