name: Run k6 soak test

on:
  workflow_run:
    workflows: [ ".NET Core Delivery Pipeline" ]
    types:
      - completed

jobs:
  soak_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Soak Test
        run: |- 
          echo "soak test todo"