name: Run k6 soak test

#on:
#  workflow_run:
#    workflows: [ ".NET Core Delivery Pipeline" ]
#    types: [completed]
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: se-jwilliams    # TODO: update to cluster name
  GKE_ZONE: us-central1-c   # TODO: update to cluster zone

jobs:
  build:
    name: K6 Soak Test
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: K6 Soak Test on GKE
        run: |-
          gcloud container clusters get-credentials se-jwilliams --zone $GKE_ZONE --project $PROJECT_ID
          cat <<EOF >soaktest-cronjob.yaml
          apiVersion: batch/v1
          kind: CronJob
          metadata:
            name: k6-loadgen-dotnet-core
          spec:
            schedule: "*/3 * * * *"
            jobTemplate:
              spec:
                template:
                  spec:
                    containers:
                    - name: k6-loadgen
                      image: loadimpact/k6
                      command: ["k6", "run", "https://raw.githubusercontent.com/cfossguy/dotnet-core/main/soakstest.js"]
                    restartPolicy: Never
          EOF
          kubectl apply -f ./soaktest-cronjob.yaml -n k6