name: Run k6 soak test

on:
  workflow_run:
    workflows: [ ".NET Core Delivery Pipeline" ]
    types: [completed]

jobs:
  soak-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Soak Test
        run: |-
          echo "soak test todo"